var annotated_dup =
[
    [ "Miniball", "namespaceMiniball.html", [
      [ "CoordAccessor", "structMiniball_1_1CoordAccessor.html", "structMiniball_1_1CoordAccessor" ],
      [ "CoordAccessor< Pit_, Cit_ * >", "structMiniball_1_1CoordAccessor_3_01Pit___00_01Cit___01_5_01_4.html", "structMiniball_1_1CoordAccessor_3_01Pit___00_01Cit___01_5_01_4" ],
      [ "Miniball", "classMiniball_1_1Miniball.html", "classMiniball_1_1Miniball" ]
    ] ],
    [ "objl", "namespaceobjl.html", [
      [ "Vector2", "structobjl_1_1Vector2.html", "structobjl_1_1Vector2" ],
      [ "Vector3", "structobjl_1_1Vector3.html", "structobjl_1_1Vector3" ],
      [ "Vertex", "structobjl_1_1Vertex.html", "structobjl_1_1Vertex" ],
      [ "Material", "structobjl_1_1Material.html", "structobjl_1_1Material" ],
      [ "Mesh", "structobjl_1_1Mesh.html", "structobjl_1_1Mesh" ],
      [ "Loader", "classobjl_1_1Loader.html", "classobjl_1_1Loader" ]
    ] ],
    [ "tinyobj", "namespacetinyobj.html", [
      [ "texture_option_t", "structtinyobj_1_1texture__option__t.html", "structtinyobj_1_1texture__option__t" ],
      [ "material_t", "structtinyobj_1_1material__t.html", "structtinyobj_1_1material__t" ],
      [ "tag_t", "structtinyobj_1_1tag__t.html", "structtinyobj_1_1tag__t" ],
      [ "index_t", "structtinyobj_1_1index__t.html", "structtinyobj_1_1index__t" ],
      [ "mesh_t", "structtinyobj_1_1mesh__t.html", "structtinyobj_1_1mesh__t" ],
      [ "shape_t", "structtinyobj_1_1shape__t.html", "structtinyobj_1_1shape__t" ],
      [ "attrib_t", "structtinyobj_1_1attrib__t.html", "structtinyobj_1_1attrib__t" ],
      [ "callback_t_", "structtinyobj_1_1callback__t__.html", "structtinyobj_1_1callback__t__" ],
      [ "MaterialReader", "classtinyobj_1_1MaterialReader.html", "classtinyobj_1_1MaterialReader" ],
      [ "MaterialFileReader", "classtinyobj_1_1MaterialFileReader.html", "classtinyobj_1_1MaterialFileReader" ],
      [ "MaterialStreamReader", "classtinyobj_1_1MaterialStreamReader.html", "classtinyobj_1_1MaterialStreamReader" ]
    ] ],
    [ "Color", "classColor.html", "classColor" ],
    [ "Cube", "classCube.html", null ],
    [ "CubeFlatIndependentScene", "classCubeFlatIndependentScene.html", "classCubeFlatIndependentScene" ],
    [ "CubeSkinScene", "classCubeSkinScene.html", "classCubeSkinScene" ],
    [ "CubeSolidGeometryScene", "classCubeSolidGeometryScene.html", "classCubeSolidGeometryScene" ],
    [ "CubeSolidScene", "classCubeSolidScene.html", "classCubeSolidScene" ],
    [ "CubeVertexColorScene", "classCubeVertexColorScene.html", "classCubeVertexColorScene" ],
    [ "CubeVertexPositionColorScene", "classCubeVertexPositionColorScene.html", "classCubeVertexPositionColorScene" ],
    [ "DefaultGeometryShader", "classDefaultGeometryShader.html", "classDefaultGeometryShader" ],
    [ "DefaultVertexShader", "classDefaultVertexShader.html", "classDefaultVertexShader" ],
    [ "DoubleCubeScene", "classDoubleCubeScene.html", "classDoubleCubeScene" ],
    [ "Engine", "classEngine.html", "classEngine" ],
    [ "EngineException", "classEngineException.html", "classEngineException" ],
    [ "FrameTimer", "classFrameTimer.html", "classFrameTimer" ],
    [ "game_state", "structgame__state.html", null ],
    [ "GDIPlusManager", "classGDIPlusManager.html", "classGDIPlusManager" ],
    [ "GeometryFlatEffect", "classGeometryFlatEffect.html", "classGeometryFlatEffect" ],
    [ "GeometryFlatScene", "classGeometryFlatScene.html", "classGeometryFlatScene" ],
    [ "Graphics", "classGraphics.html", "classGraphics" ],
    [ "HWNDKey", "classHWNDKey.html", "classHWNDKey" ],
    [ "IndexedTriangleList", "structIndexedTriangleList.html", "structIndexedTriangleList" ],
    [ "Keyboard", "classKeyboard.html", "classKeyboard" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "Matrix2", "classMatrix2.html", "classMatrix2" ],
    [ "Matrix3", "classMatrix3.html", "classMatrix3" ],
    [ "Mouse", "classMouse.html", "classMouse" ],
    [ "Pipeline", "classPipeline.html", "classPipeline" ],
    [ "Plane", "classPlane.html", null ],
    [ "PubeScreenTransformer", "classPubeScreenTransformer.html", "classPubeScreenTransformer" ],
    [ "Scene", "classScene.html", "classScene" ],
    [ "SolidEffect", "classSolidEffect.html", "classSolidEffect" ],
    [ "SolidGeometryEffect", "classSolidGeometryEffect.html", "classSolidGeometryEffect" ],
    [ "Surface", "classSurface.html", "classSurface" ],
    [ "TextureEffect", "classTextureEffect.html", "classTextureEffect" ],
    [ "TexVertex", "classTexVertex.html", "classTexVertex" ],
    [ "Triangle", "classTriangle.html", "classTriangle" ],
    [ "Vector2", "classVector2.html", "classVector2" ],
    [ "Vector3", "classVector3.html", "classVector3" ],
    [ "Vector4", "classVector4.html", "classVector4" ],
    [ "VertexColorEffect", "classVertexColorEffect.html", "classVertexColorEffect" ],
    [ "VertexFlatEffect", "classVertexFlatEffect.html", "classVertexFlatEffect" ],
    [ "VertexPositionColorEffect", "classVertexPositionColorEffect.html", "classVertexPositionColorEffect" ],
    [ "VertexWaveScene", "classVertexWaveScene.html", "classVertexWaveScene" ],
    [ "WaveVertexTextureEffect", "classWaveVertexTextureEffect.html", "classWaveVertexTextureEffect" ],
    [ "ZBuffer", "classZBuffer.html", "classZBuffer" ]
];